[package]
name = "spf-check"
version = "0.1.1"
edition = "2021"

[dependencies]
decon-spf = "0.3.3"
trust-dns-resolver = { version = "0.23.2", features = ["tokio-runtime"] }
futures = "0.3.31"
tokio = { version = "1.44.2", features = ["full"] }
axum = "0.8.3"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.98"
http = "1.3.1"
chrono = "0.4.40"

[profile.release]
lto = true
codegen-units = 1
