### GET request to server for easybill.de (positive)
GET http://localhost:8080/api/v1/check-spf?domain=easybill.de&target=_spf.easybill.de

> {%
    client.test("Status code is 200", () => client.assert(response.status === 200));

    client.test("Response JSON is valid", () => {
        client.assert(response.body.found);
        client.assert(response.body.checked_domains === 1);
        client.assert(response.body.spf_record.includes('include:_spf.easybill.de'));
        client.assert(response.body.included_domains.length === 4);
    });
%}

### GET request to server for google.com (negative)
GET http://localhost:8080/api/v1/check-spf?domain=google.com&target=_spf.easybill.de

> {%
    client.test("Status code is 200", () => client.assert(response.status === 200));

    client.test("Response JSON is valid", () => {
        client.assert(!response.body.found);
        client.assert(response.body.checked_domains === 1);
        client.assert(response.body.spf_record === "v=spf1 include:_spf.google.com ~all");
        client.assert(response.body.included_domains.length === 1 && response.body.included_domains[0] === "_spf.google.com");
    });
%}

### GET health
GET http://localhost:8080/health

> {%
    client.test("Status code is 200", () => client.assert(response.status === 200));
%}


### GET request to server with a redirect
GET http://localhost:8080/api/v1/check-spf?domain=top21.sh&target=_spf.easybill.de

> {%
    client.test("Status code is 200", () => client.assert(response.status === 200));

    client.test("Response JSON is valid", () => {
        client.assert(!response.body.found);
        client.assert(response.body.checked_domains === 1);
        client.assert(response.body.spf_record === "v=spf1 redirect=_sfjzzyuj0.sdmarc.net");
        client.assert(response.body.included_domains.length === 0);
    });
%}
