name: update-dockerhub-readme

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "Logging into Docker Hub..."
          TOKEN=$(curl -s -H "Content-Type: application/json" \
            -d '{"username": "'"$DOCKERHUB_USERNAME"'", "password": "'"$DOCKERHUB_TOKEN"'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          
          echo "Updating Docker Hub description..."
          curl -s -X PATCH \
            -H "Authorization: JWT $TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"full_description": "'"$(<README.md)"'"}' \
            https://hub.docker.com/v2/repositories/easybill/spf-check/
